"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: DocumentModule
  IDL file: document.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import DocumentModule


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Document(idl.IdlStruct, typename="DocumentModule.Document"):
    recipient: types.bounded_str[255]
    annotate.key("recipient")
    subject: types.bounded_str[255]
    url: types.bounded_str[255]


